services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: earthquake_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: earthquake_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
  mariadb:
    image: mariadb:10.11
    container_name: earthquake_mariadb
    ports:
      - "3306:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=100'
      - '--binlog-format=ROW'
      - '--log-bin=mariadb-bin'
      - '--binlog-do-db=earthquake'
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: earthquake
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  postgres:
    image: postgres:15
    container_name: earthquake_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthquake_sink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d earthquake_sink"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
      
  kafka-connect:
    image: debezium/connect:2.4
    container_name: earthquake_kafka-connect
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: earthquake-cdc
      CONFIG_STORAGE_TOPIC: earthquake-cdc-configs
      OFFSET_STORAGE_TOPIC: earthquake-cdc-offsets
      STATUS_STORAGE_TOPIC: earthquake-cdc-status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s