# Note: The top-level 'version' attribute is obsolete in modern Docker Compose and has been removed.

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: earthquake_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: earthquake_kafka
    restart: always
    ports:
      # Port for external connections from your host machine (e.g., Python script, admin tools)
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Advertised listeners tell clients how to connect.
      # PLAINTEXT is for internal connections within the Docker network (e.g., from Kafka Connect).
      # PLAINTEXT_HOST is for external connections from your host machine.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mariadb:
    image: mariadb:10.11
    container_name: earthquake_mariadb
    restart: always
    ports:
      - "3306:3306"
    # Command arguments enable binary logging, which is required for Debezium CDC.
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=100'
      - '--binlog-format=ROW'
      - '--log-bin=mariadb-bin'
      - '--binlog-do-db=earthquake'
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: earthquake
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:15
    container_name: earthquake_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthquake_sink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d earthquake_sink"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  kafka-connect:
    build:
      context: ./kafka-connect
    image: earthquake_kafka-connect
    container_name: earthquake_kafka-connect
    restart: always
    ports:
      - "8083:8083" # Kafka Connect REST API
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_GROUP_ID: "earthquake-cdc"

      # --- NEWLY ADDED SETTINGS ---
      # These tell the worker how to advertise its own REST API to other services.
      # Use the container's service name for the hostname.
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_PORT: 8083

      # Topics for Connect to store its configuration, offsets, and status.
      CONNECT_CONFIG_STORAGE_TOPIC: "earthquake-cdc-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "earthquake-cdc-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "earthquake-cdc-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # Default converters
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s