# Note: The 'version' tag is obsolete and not needed.
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: earthquake_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: earthquake_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
  mariadb:
    # --- CORRECTED INDENTATION ---
    image: mariadb:10.11
    container_name: earthquake_mariadb
    ports:
      - "3306:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--server-id=100'
      - '--binlog-format=ROW'
      - '--log-bin=mariadb-bin'
      - '--binlog-do-db=earthquake'
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: earthquake
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  postgres:
    image: postgres:15
    container_name: earthquake_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthquake_sink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d earthquake_sink"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
      
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: earthquake_kafka-connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
      - mariadb
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "earthquake-cdc"
      CONNECT_CONFIG_STORAGE_TOPIC: "earthquake-cdc-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "earthquake-cdc-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "earthquake-cdc-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/kafka/connect/debezium"
    volumes:
      - ./connectors:/kafka/connect/debezium